version: "3"

services:
  dpfm-ui:
#    image: node:17.6-slim
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_TARGET=${ENV_TARGET}
    container_name: dpfm-ui
    restart: always
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev:${ENV_TARGET}
    env_file:
      - docker/.env
    ports:
      - "3001:3001"
